- shell:
    - ['sudo apt install -y libsecret-tools libkrb5-dev krb5-user python3-pip python3-ldap python3-winrm', Install deps]
    - ['python3 -m pip install --user ansible', Install ansible]

- create:
    - ~/.local/bin

- link:
    ~/.local/bin/vault-env: apps/ansible/vault-env
