- shell:
    - ['sudo apt install -y git', Install deps]

- link:
    ~/.gitconfig:
        path: apps/git/gitconfig

    ~/.config/git/ignore:
        path: apps/git/ignore
        force: true
        create: true
