- shell:
    - ['sudo apt install -y git curl libsecret-tools fzf tmux', Install deps]

- create:
    - ~/.local/etc/sh.d

- link:
    ~/.profile:
        path: shells/profile
        force: true

    ~/.hushlogin:
        path: shells/hushlogin
        force: true

    ~/.local/etc/sh.d/10-env.sh:
        path: shells/sh.d/10-env.sh
        create: true
        force: true

    ~/.local/etc/sh.d/20-funcs.sh:
        path: shells/sh.d/20-funcs.sh
        create: true
        force: true

    ~/.local/etc/sh.d/50-nvm.sh:
        path: shells/sh.d/50-ssh-tmux.sh
        create: true
        force: true

    ~/.local/etc/sh.d/50-php-docker-xdebug.sh:
        path: shells/sh.d/50-php-docker-xdebug.sh
        create: true
        force: true

    ~/.local/etc/sh.d/50-ssh-tmux.sh:
        path: shells/sh.d/50-ssh-tmux.sh
        create: true
        force: true

    ~/.local/bin/edit:
        path: apps/local/edit
        create: true
        force: true

    ~/.local/bin/get-github-keys:
        path: apps/local/get-github-keys
        create: true
        force: true
