
- shell: 
    - ['[ -d "$HOME/.tmux/plugins/tpm" ] || git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm', install tpm]
    - ['TMUX_PLUGIN_MANAGER_PATH=$HOME/.tmux/plugins/tpm ~/.tmux/plugins/tpm/bin/update_plugins all', update tpm plugins]

- link:
    ~/.tmux.conf: apps/tmux/tmux.conf
