# ~/.zshenv - This is loaded universally for all types of shell sessions
#             (interactive or non-interactive, login or non-login)

if [ -d "$HOME/.local/etc/zshenv.d" ]; then
  for i in "$HOME/.local/etc/zshenv.d/"*; do
    [ -f "$i" ] && source "$i"
  done
  unset i
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
