#!/usr/bin/env bash

[ ! -z "$WSL_DISTRO_NAME" ] || return 0

# if [ "$XDG_RUNTIME_DIR" != "/mnt/wslg/runtime-dir" ]; then
#     export DISPLAY=:0.0
#     # somtimes dbus is not up yet from systemd, wait for it
#     NEXT_WAIT_TIME=0
#     until [ $NEXT_WAIT_TIME -eq 5 ] || pgrep -u $UID dbus >/dev/null; do
#         sleep $(( NEXT_WAIT_TIME++ ))
#     done
#     [ $NEXT_WAIT_TIME -lt 5 ] && dbus-update-activation-environment --systemd --all
#     unset NEXT_WAIT_TIME
# fi

export WSL_HOST_IP=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}')
export WSL_CLIENT_IP=$(ip -4 addr show eth0 | grep -Po 'inet \K[\d.]+')

if [ -d "$HOME/winhome" ] ; then
    export WINHOME="$HOME/winhome"
fi

if [ command -v wslview &> /dev/null ]; then
    export BROWSER=wslview
fi

if [ -d "$HOME/.local/share/JetBrains/Toolbox/bin" ] ; then
    PATH="$HOME/.local/share/JetBrains/Toolbox/bin:$PATH"
fi

if [ -d "$HOME/.local/share/JetBrains/Toolbox/scripts" ] ; then
    PATH="$HOME/.local/share/JetBrains/Toolbox/scripts:$PATH"
fi

if [ -e $HOME/.local/bin/vault-env ]; then
    export ANSIBLE_VAULT_PASSWORD_FILE=$HOME/.local/bin/vault-env
fi

export GNOME_KEYRING_CONTROL=$XDG_RUNTIME_DIR/keyring
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh
export GTK_THEME=Adwaita:dark
